<?php
       include '../include/PHPExcel/PHPExcel.php';
       include '../include/PHPExcel/PHPExcel/Writer/Excel2007.php';
       
        $export = $_POST['export'];
        if($export=='1') {
            $name = $_POST['name'];
            $data = unserialize(base64_decode($_POST['data']));
            $format = unserialize(base64_decode($_POST['format']));
            downloadExcel($name, $data, $format);
        }  
        
        $objPHPExcel = new PHPExcel();
        
        function downloadExcel($name, $data, $format){
            $objPHPExcel = createExcelSpreadsheet($name, $data, $format);
            downloadFromBrowser($objPHPExcel, $name);
        }
        
        function emailExcel($name, $data, $format, $from, $reply, $cc, $bcc, $emails, $subject, $message){
            $objPHPExcel = createExcelSpreadsheet($name, $data, $format);
            return sendInEmail($objPHPExcel, $name, $from, $reply, $cc, $bcc, $emails, $subject, $message);
        }
            
            
        function createExcelSpreadsheet($name, $data, $format){
            $objPHPExcel = new PHPExcel();
            $cols =  sizeof($data);
            
            //Set properties
            $objPHPExcel->getProperties()->setCreator("CMS")
                 ->setLastModifiedBy("CMS")
                 ->setTitle($name)
                 ->setSubject("")
                 ->setDescription("Excel spreadsheet auto-generated by CMS.")
                 ->setCategory("Auto-Generated");

            //Add data
            $objPHPExcel->setActiveSheetIndex(0);
            $max_col = chr(64 + sizeof($data));
            $max_row = sizeof($data[0]);
            //columns
            for($i=0; $i<sizeof($data); $i++){
                $col = chr(65 + $i);
                //rows
                for($j=0; $j<sizeof($data[$i]); $j++){
                    $objPHPExcel->getActiveSheet()->setCellValueByColumnAndRow($i, $j+1, $data[$i][$j]);
                }
                //columns
                $objPHPExcel->getActiveSheet()->getColumnDimension($col)->setAutoSize(true);
                $objPHPExcel->getActiveSheet()->getStyle($col)->getAlignment()->setHorizontal(PHPExcel_Style_Alignment::HORIZONTAL_LEFT);
                $objPHPExcel->getActiveSheet()->getStyle($col.'1:'.$col.$max_row)->getNumberFormat()->setFormatCode($format[$i]);//PHPExcel_Style_NumberFormat::
            }
            
            //Set formatting
            //headers
            $headerStyle = array(
                'font' => array(
                    'color' => array(
                            'argb' => 'FFFFFFFF',
                    ),
                    'size' => '14'
                ),
                'alignment' => array(
                    'horizontal' => PHPExcel_Style_Alignment::HORIZONTAL_CENTER,
                ),
                'fill' => array(
                    'type' => PHPExcel_Style_Fill::FILL_SOLID,
                    'startcolor' => array(
                            'argb' => 'FF244062',
                    )
                )
            );
            $objPHPExcel->getActiveSheet()->getStyle('A1:'.$max_col.'1')->applyFromArray($headerStyle);

            
            $objPHPExcel->getActiveSheet()->setTitle('Data');

            $objPHPExcel->setActiveSheetIndex(0);
            
            return $objPHPExcel;
       }
       
       function downloadFromBrowser($objPHPExcel, $name){
            // Redirect output to a client’s web browser (Excel5)
            header('Content-Type: application/vnd.ms-excel');
            header('Content-Disposition: attachment;filename="'.$name.'.xls"');
            header('Cache-Control: max-age=0');

            $objWriter = PHPExcel_IOFactory::createWriter($objPHPExcel, 'Excel5');
            $objWriter->save('php://output');
            exit;
        }
        
        function sendInEmail($objPHPExcel, $name, $from, $reply, $cc, $bcc, $emails, $subject, $message){
            include 'PHPExcel/IOFactory.php';
            
            $objWriter = PHPExcel_IOFactory::createWriter($objPHPExcel, 'Excel5');
            $objWriter->save('../Misc/files/NBCal/'.$name.'.xls');
            
            include 'email.php';
            return sendEmailWithAttachment($from, $reply, $cc, $bcc, $emails, $subject, $message, "application/vnd.ms-excel", "$name.xls", file_get_contents('../Misc/files/NBCal/'.$name.'.xls'));
        }
?>