<?php
        require_once '../include/PHPExcel/PHPExcel.php';

        // Create new PHPExcel object
        $objPHPExcel = new PHPExcel();

        // Set properties
        $objPHPExcel->getProperties()->setCreator("William Atkinson")
             ->setLastModifiedBy("William Atkinson")
             ->setTitle("Test")
             ->setSubject("")
             ->setDescription("Excel spreadsheet auto generated by CMS.")
             ->setCategory("Auto Generated");

        $style = unserialize(base64_decode($_POST['style']));
        $format = unserialize(base64_decode($_POST['format']));
        $data = unserialize(base64_decode($_POST['data']));
        $name = "Sample Spreadsheet";
        $name = $_POST['name'];
        $cols =  sizeof($data);
        
        //style column headings
        $headingStyle = array(
                'font' => array(
                    'bold' => true,
                    'color' => array(
                        'argb' => 'FFFBC497',
                    ),
                ),
                'alignment' => array(
                    'horizontal' => PHPExcel_Style_Alignment::HORIZONTAL_CENTER,
                ),
                'fill' => array(
                    'type' => PHPExcel_Style_Fill::FILL_SOLID,
                    'startcolor' => array(
                        'argb' => 'FF0242A0',
                    ),
                ),
        );
        $objPHPExcel->getActiveSheet()->getStyle('A1:'.chr(64 + $cols).'1')->applyFromArray($headingStyle);
        
        //auto size all columns
        $objPHPExcel->getActiveSheet()->getColumnDimension('A:'.chr(64 + sizeof($data)))->setAutoSize(true);
        
        //add custom formats
        for($i=0; $i<$cols; $i++){
            //'$#,##0.00'
            $objPHPExcel->getActiveSheet()->getStyle(chr(65+$i))->getNumberFormat()->setFormatCode($format[$i]);
            $objPHPExcel->getActiveSheet()->getStyle(chr(65+$i))->applyFromArray($style[$i]);
        }
        
        //data
        //columns
        for($i=0; $i<sizeof($data); $i++){
            //rows
            for($j=0; $j<sizeof($data[$i]); $j++){
                $objPHPExcel->getActiveSheet()->setCellValueByColumnAndRow($i, $j+1, $data[$i][$j]);
            }
        }
        
        // Rename sheet
        $objPHPExcel->getActiveSheet()->setTitle('Simple');

        // Set active sheet index to the first sheet, so Excel opens this as the first sheet
        $objPHPExcel->setActiveSheetIndex(0);


        // Redirect output to a clientâ€™s web browser (Excel5)
        header('Content-Type: application/vnd.ms-excel');
        header("Content-Disposition: attachment;filename='$name.xls'");
        header('Cache-Control: max-age=0');

        $objWriter = PHPExcel_IOFactory::createWriter($objPHPExcel, 'Excel5');
        $objWriter->save('php://output');
        readfile('php://output');   
?>
